### PR TITLE
@orta => [ARLabelWithChevron] Inset text to not overlap chevron.

### PR DESCRIPTION
**Pull request by alloy**
This fixes https://github.com/artsy/eigen/issues/312

### CODE REVIEW

**Comment by alloy** [comment]
Oh! I thought there were no tests at all, but I now see they’re inside the example app.

**Comment by 1aurabrown** [comment]
Yeah, there are some snapshot tests. Might be a good idea to add one.what happens if a labrl is constrained to some width, and then the text width + the chevron width exceed that constraint, does it wrap, or take precedence over the constraint, or get squished anyway?

**Comment by 1aurabrown** [comment]
Sorry about the typos, i'm on my phone

**Comment by 1aurabrown** [comment]
Also you might have to change the eigen podfile to point to this commit (when merged) if it isn't already pointing to :head, or we can release a new version of this pod and point to that version number.  Sent using CloudMagicOn Thu, Mar 26, 2015 at 14:37,  artsy/Artsy-UILabels <reply@reply.github.com> wrote:            Oh! I thought there were no tests at all, but I now see they’re inside the example app.

**Comment by alloy** [comment]
> What happens if a label is constrained to some width, and then the text width + the chevron width exceed that constraint, does it wrap, or take precedence over the constraint, or get squished anyway?

@1aurabrown Not sure I fully follow the question, does [the new snapshot](https://github.com/artsy/Artsy-UILabels/blob/9ada2bca4e4374276b05b3bd7320a56b8ae1e95c/Example/Tests/ReferenceImages/LabelSpecsSpec/label_subclasses_ARLabelWithChevron_ensures_the_text_is_truncated_before_the_chevron%402x.png) answer your question?

**Comment by 1aurabrown** [comment]
Yeah. The chevron looks clipped in the snapshot, is that expected?

**Comment by alloy** [comment]
Nope, not at all. Good catch, it works as expected in Eigen. I’ll look into that further in the morning.

**Comment by alloy** [comment]
Ok, the test suite is now green again.

**Comment by alloy** [comment]
I fixed the chevron clipping.

Regarding other issues such as wrapping, it should work as normal, expect that the area where text will be drawn is inset. Is this label being used with multi-line text somewhere?

**Comment by alloy** [comment]
On the topic of a new release, I think we can point to head and if after Q&A everything turns out to be fine we can do a release?

**Comment by alloy** [comment]
Btw this also supersedes #12.

**Comment by orta** [comment]
Looks cool 👍

**Comment by 1aurabrown** [comment]
oops sorry! looks good

**Pull request merged**
