### PR TITLE
@orta => Ensure dollar amounts always format with dollar sign

### PR DESCRIPTION
**Pull request by alloy**
Fixes https://github.com/artsy/eigen/issues/760

I also deprecated a method that did not include the name of the currency.

### CODE REVIEW

**Comment by orta** [comment]
This looks :+1:  to me, merge on green

**Comment by orta** [comment]
I feel like the Xcode being used by travis isn't the same as yours

**Comment by alloy** [comment]
Hmm, this is failing the two snapshot tests that needed updating with Xcode 6.4. What shall I do, revert those?

**Comment by alloy** [comment]
Yeah, they’re still on Xcode 6.1, I’m on 6.4.

**Comment by alloy** [comment]
Green, merging!

**Pull request merged**
