### PR TITLE
Relies on OSS fonts for non-Artsy staff.

### PR DESCRIPTION
**Pull request by ashfurrow**
Based on @orta's suggestion in this issue: https://github.com/artsy/eidolon/issues/625

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hmm, needs a version bump and changelog entry.

**Comment by orta** [comment]
👍 good to go on green

**Comment by ashfurrow** [comment]
Looks like it's still on 0.39, an update should fix it eh?

**Comment by ashfurrow** [comment]
Fingers crossed 😄

**Comment by ashfurrow** [comment]
Yay green! Gonna wait for Orta to re-review since this pr has expanded considerably in scope.

**Comment by orta** [comment]
Cool, looks legit

**Pull request merged**
