### PR TITLE
Set preferred width when the layout changes.

### PR DESCRIPTION
**Pull request by alloy**
Fixes https://github.com/artsy/eigen/issues/1311

### CODE REVIEW

**Comment by sarahscott** [comment]
Fail legit

**Comment by alloy** [comment]
Ok, this change is causing Eigen’s test suite to hang during layout passes and I haven’t yet figured out why that is, so leaving this be for now.

**Comment by sarahscott** [comment]
:ok_hand:

**Comment by orta** [comment]
deprecated by #22

**Pull request closed without merging**
